<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_AutomaticFlowControlHandler_Test" Id="{43cf9b37-2317-4a83-833a-9888f010061c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_AutomaticFlowControlHandler_Test EXTENDS TcUnit.FB_TestSuite
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_AutomaticFlowControlHandler_Test">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>