<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="AutomaticFlowControlHandler" Id="{1d683a84-77f3-4fa0-9fcb-6c948632e209}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK AutomaticFlowControlHandler
VAR_OUTPUT
	controlValvePercentage : INT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="AutomaticFlowControlHandler">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>