<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="TemperatureControl" Id="{f71717d9-deae-438c-aba5-3161ba70bdae}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM TemperatureControl
VAR
	fbTemperaturePIDControl	: FB_TemperaturePIDControl;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//fbTemperaturePIDControl();
]]></ST>
    </Implementation>
    <LineIds Name="TemperatureControl">
      <LineId Id="5" Count="0" />
      <LineId Id="10" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>