<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_SerialController" Id="{d2970343-d39c-46df-9e3f-e9dac4aaac85}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_SerialController
VAR_INPUT
	slaveNumber : INT;
END_VAR
VAR
	//fbEL6001	: FB_SerialCom;
	
	fbAsciiComm: FB_SerialCom;
	

	ReceiveStep: INT;
	ProcessVariableRead : BOOL;
	SetpointRead : BOOL;
	ProcessVariableReceived : BOOL;
	SetpointReceived : BOOL;
	SendStep: INT;
	bStartSend: BOOL;
	start3: BOOL;
	received3: BOOL;
	start4: BOOL;
	received4: BOOL;
	Setpoint: STRING;
	
	fbUpdateSetpoint: FB_UpdateSetpoint;
	pumpingPressureMeasurement: DINT;
	pumpingPressureSetpoint: DINT;
	pumpingPressureSetSetpoint: DINT;
	pumpingPressureSetSetpointPrev: DINT;
	tonMessageUpdate: TON;
	rTrigMessageNotUpdated: R_TRIG;
	OutputPowerRead: BOOL;
	OutputPowerReceived: BOOL;
	pumpingPressureOutputPower: DINT;
	testi: BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_SerialController">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>