<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="MAIN" Id="{dec5b1ca-8e16-4f49-8efb-57a750654862}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	rInput: REAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Control functions

//ReactorTemperatureControl();
ReactorTemperature();

ReactorLevelAndPressure();
//ReactorLevelAndPressureControl();
// MATLAB functions
DataAcquisition();
// Persist set variables
VariablePersistence();
// Serial communications
SerialCommunicationHandler();
// Safety
Safety();

MainScreenBindings();
ProcessViewBindings();
ParameterViewBindings();
//PidParameterMenuBindings();
//AutoExtractionParameterMenuBindings();
//ExtractiveOutletValveParameterMenuBindings();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="189" Count="2" />
      <LineId Id="239" Count="1" />
      <LineId Id="193" Count="0" />
      <LineId Id="234" Count="0" />
      <LineId Id="194" Count="5" />
      <LineId Id="262" Count="1" />
      <LineId Id="201" Count="1" />
      <LineId Id="261" Count="0" />
      <LineId Id="256" Count="0" />
      <LineId Id="246" Count="0" />
      <LineId Id="245" Count="0" />
      <LineId Id="251" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>